language: c

addons:
  postgresql: "9.3"

install:
  - sudo apt-get install luarocks
  - mkdir -p ~/.luarocks
  - echo 'rocks_servers = { "http://luarocks.org" }' > ~/.luarocks/config.lua
  - sudo luarocks install luasec
  - sudo luarocks install https://luarocks.org/manifests/olivine-labs/busted-2.0.rc11-0.rockspec
  - sudo luarocks install moonscript
  - sudo luarocks install luacrypto
  - sudo luarocks install luaposix
  - sudo luarocks install date
  - sudo luarocks make
  - cat $(which busted) | sed 's/\/usr\/bin\/lua/.\/luajit/' > busted
  - chmod +x busted
  - ./install_luajit.sh
  - createdb -U postgres lapis_test

script: ./busted && ./busted spec_postgres/
